#!/bin/bash
#
# Cursor Sandbox Setup (run once)
#
# Validates prerequisites, creates required directories, and writes
# a config file used by cursor-sandbox.sh.
#
# Re-run this script after changing CURSOR_APPIMAGE, WORKSPACE_DIR,
# or moving the Cursor AppImage to a new location.
#

set -e

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(dirname "$SCRIPT_PATH")"
APPIMAGE_DIR="$HOME/.local/opt/cursor"
CONFIG_FILE="${SCRIPT_DIR}/.cursor-sandbox.env"

CURSOR_APPIMAGE="${CURSOR_APPIMAGE:-$(ls -t "$APPIMAGE_DIR"/Cursor-*.AppImage 2>/dev/null | head -1)}"

if [ -z "$WORKSPACE_DIR" ]; then
    read -rp "Enter workspace directory [$HOME/proj]: " WORKSPACE_DIR
    WORKSPACE_DIR="${WORKSPACE_DIR:-$HOME/proj}"
fi

PROFILE="${SCRIPT_DIR}/cursor.firejail.profile"

# ── Check prerequisites ──────────────────────────────────────────────
if ! command -v firejail &> /dev/null; then
    echo "Error: firejail is not installed"
    echo "Install it with: sudo apt install firejail   (Debian/Ubuntu)"
    echo "                 sudo dnf install firejail   (Fedora)"
    echo "                 sudo pacman -S firejail     (Arch Linux)"
    exit 1
fi

if [ ! -f "$PROFILE" ]; then
    echo "Error: Firejail profile not found at: $PROFILE"
    echo "Ensure cursor.firejail.profile is in the same directory as this script."
    exit 1
fi

if [ -z "$CURSOR_APPIMAGE" ] || [ ! -f "$CURSOR_APPIMAGE" ]; then
    echo "Error: No Cursor AppImage found."
    echo "Place a Cursor-*.AppImage in $APPIMAGE_DIR/"
    echo "or set CURSOR_APPIMAGE=/path/to/Cursor.AppImage"
    exit 1
fi

chmod +x "$CURSOR_APPIMAGE"
CURSOR_APPIMAGE="$(readlink -f "$CURSOR_APPIMAGE")"
WORKSPACE_DIR="$(readlink -f "$WORKSPACE_DIR")"

# ── Create required directories ───────────────────────────────────────
mkdir -p "$APPIMAGE_DIR" \
         "$HOME/.cursor" \
         "$HOME/.cursor-server" \
         "$HOME/.config/Cursor" \
         "$HOME/.local/share/Cursor" \
         "$HOME/.cache/Cursor" \
         "$WORKSPACE_DIR"

# ── Write config file ────────────────────────────────────────────────
cat > "$CONFIG_FILE" <<EOF
# Generated by cursor-sandbox-setup.sh -- re-run setup to regenerate
CURSOR_APPIMAGE="$CURSOR_APPIMAGE"
WORKSPACE_DIR="$WORKSPACE_DIR"
PROFILE="$PROFILE"
EOF

echo "Setup complete. Config written to: $CONFIG_FILE"
echo "  AppImage:  $CURSOR_APPIMAGE"
echo "  Workspace: $WORKSPACE_DIR"
echo "  Profile:   $PROFILE"
